"""initial_migration_setup_tables

Revision ID: 001
Revises: 
Create Date: YYYY-MM-DD HH:MM:SS.ffffff

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Table: claimants
    op.create_table('claimants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now(), onupdate=sa.func.now()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claimants_email'), 'claimants', ['email'], unique=True)
    op.create_index(op.f('ix_claimants_id'), 'claimants', ['id'], unique=False) # Standard practice to index PK
    op.create_index(op.f('ix_claimants_name'), 'claimants', ['name'], unique=False) # As per SQLClaimant model

    # Table: claimant_documents
    op.create_table('claimant_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('claimant_id', sa.Integer(), nullable=False),
        sa.Column('document_type', sa.String(length=50), nullable=False),
        sa.Column('file_path', sa.String(length=512), nullable=True),
        sa.Column('raw_text_content', sa.Text(), nullable=True),
        sa.Column('parsed_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('uploaded_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(['claimant_id'], ['claimants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claimant_documents_id'), 'claimant_documents', ['id'], unique=False)
    # Add other indexes if defined in model, e.g., for claimant_id or document_type

    # Table: job_postings
    op.create_table('job_postings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('company_name', sa.String(length=255), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('job_url', sa.String(length=2048), nullable=False),
        sa.Column('source_website', sa.String(length=255), nullable=True),
        sa.Column('date_scraped', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('date_posted', sa.Date(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_index(op.f('ix_job_postings_job_url'), 'job_postings', ['job_url'], unique=True)
    # Add other indexes as per SQLJobPosting model, e.g. date_posted, source_website
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop in reverse order of creation

    # Job Postings
    op.drop_index(op.f('ix_job_postings_job_url'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_table('job_postings')

    # Claimant Documents
    op.drop_index(op.f('ix_claimant_documents_id'), table_name='claimant_documents')
    op.drop_table('claimant_documents')

    # Claimants
    op.drop_index(op.f('ix_claimants_name'), table_name='claimants')
    op.drop_index(op.f('ix_claimants_id'), table_name='claimants')
    op.drop_index(op.f('ix_claimants_email'), table_name='claimants')
    op.drop_table('claimants')
    # ### end Alembic commands ###
