"""add_location_keywords_to_claimant

Revision ID: 002
Revises: 001 
Create Date: YYYY-MM-DD HH:MM:SS.ffffff # Replace with actual date

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001' # Should point to the previous migration (e.g., '001_initial_migration')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make sure to use the correct table name, which is 'claimants'
    # as defined in the SQLClaimant model.
    op.add_column('claimants', sa.Column('target_location', sa.String(), nullable=True))
    op.add_column('claimants', sa.Column('search_keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make sure to use the correct table name
    op.drop_column('claimants', 'search_keywords')
    op.drop_column('claimants', 'target_location')
    # ### end Alembic commands ###
